//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lookup
{
    using System.Net.Security;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CprByCvrAndRidResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class CprByCvrAndRidResponse : object
    {
        
        private string CprField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpr
        {
            get
            {
                return this.CprField;
            }
            set
            {
                this.CprField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CprByPidResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class CprByPidResponse : object
    {
        
        private string CprField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpr
        {
            get
            {
                return this.CprField;
            }
            set
            {
                this.CprField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CprUuidBySubjectSerialNumberResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class CprUuidBySubjectSerialNumberResponse : object
    {
        
        private System.Guid CprUuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CprUuid
        {
            get
            {
                return this.CprUuidField;
            }
            set
            {
                this.CprUuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CprBySubjectSerialNumberResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class CprBySubjectSerialNumberResponse : object
    {
        
        private string CprField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpr
        {
            get
            {
                return this.CprField;
            }
            set
            {
                this.CprField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RidBySubjectSerialNumberResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class RidBySubjectSerialNumberResponse : object
    {
        
        private string RidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rid
        {
            get
            {
                return this.RidField;
            }
            set
            {
                this.RidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PidByCprResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class PidByCprResponse : object
    {
        
        private string PidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pid
        {
            get
            {
                return this.PidField;
            }
            set
            {
                this.PidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PidMatchesCprResponse", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public partial class PidMatchesCprResponse : object
    {
        
        private Lookup.PidMatchesCprResult ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Lookup.PidMatchesCprResult Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PidMatchesCprResult", Namespace="http://schemas.datacontract.org/2004/07/Nemlogin.EIA.Contracts.DataTransferObject" +
        "s.Lookup")]
    public enum PidMatchesCprResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Match = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMatch = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCpr = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        TooManyFailedMatchRequests = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lookupservice.nemlog-in.dk", ConfigurationName="Lookup.LookupService")]
    public interface LookupService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/RidCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/RidCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.RidCprResponse RidCpr(Lookup.RidCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/RidCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/RidCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.RidCprResponse> RidCprAsync(Lookup.RidCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/PidCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/PidCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.PidCprResponse PidCpr(Lookup.PidCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/PidCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/PidCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.PidCprResponse> PidCprAsync(Lookup.PidCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCprUuid", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCprUuidRespons" +
            "e", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.SubjectSerialNumberCprUuidResponse SubjectSerialNumberCprUuid(Lookup.SubjectSerialNumberCprUuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCprUuid", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCprUuidRespons" +
            "e", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.SubjectSerialNumberCprUuidResponse> SubjectSerialNumberCprUuidAsync(Lookup.SubjectSerialNumberCprUuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.SubjectSerialNumberCprResponse SubjectSerialNumberCpr(Lookup.SubjectSerialNumberCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.SubjectSerialNumberCprResponse> SubjectSerialNumberCprAsync(Lookup.SubjectSerialNumberCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberRid", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberRidResponse", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.SubjectSerialNumberRidResponse SubjectSerialNumberRid(Lookup.SubjectSerialNumberRidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberRid", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/SubjectSerialNumberRidResponse", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.SubjectSerialNumberRidResponse> SubjectSerialNumberRidAsync(Lookup.SubjectSerialNumberRidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/CprPid", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/CprPidResponse", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.CprPidResponse CprPid(Lookup.CprPidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/CprPid", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/CprPidResponse", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.CprPidResponse> CprPidAsync(Lookup.CprPidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/PidMatchesCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/PidMatchesCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        Lookup.PidMatchesCprResponse1 PidMatchesCpr(Lookup.PidMatchesCprRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lookupservice.nemlog-in.dk/LookupService/PidMatchesCpr", ReplyAction="http://lookupservice.nemlog-in.dk/LookupService/PidMatchesCprResponse", ProtectionLevel = ProtectionLevel.Sign)]
        System.Threading.Tasks.Task<Lookup.PidMatchesCprResponse1> PidMatchesCprAsync(Lookup.PidMatchesCprRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RidCpr", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class RidCprRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string cvr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=1)]
        public string rid;
        
        public RidCprRequest()
        {
        }
        
        public RidCprRequest(string cvr, string rid)
        {
            this.cvr = cvr;
            this.rid = rid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RidCprResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class RidCprResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.CprByCvrAndRidResponse RidCprResult;
        
        public RidCprResponse()
        {
        }
        
        public RidCprResponse(Lookup.CprByCvrAndRidResponse RidCprResult)
        {
            this.RidCprResult = RidCprResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PidCpr", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class PidCprRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string pid;
        
        public PidCprRequest()
        {
        }
        
        public PidCprRequest(string pid)
        {
            this.pid = pid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PidCprResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class PidCprResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.CprByPidResponse PidCprResult;
        
        public PidCprResponse()
        {
        }
        
        public PidCprResponse(Lookup.CprByPidResponse PidCprResult)
        {
            this.PidCprResult = PidCprResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubjectSerialNumberCprUuid", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class SubjectSerialNumberCprUuidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string subjectSerialNumber;
        
        public SubjectSerialNumberCprUuidRequest()
        {
        }
        
        public SubjectSerialNumberCprUuidRequest(string subjectSerialNumber)
        {
            this.subjectSerialNumber = subjectSerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubjectSerialNumberCprUuidResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class SubjectSerialNumberCprUuidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.CprUuidBySubjectSerialNumberResponse SubjectSerialNumberCprUuidResult;
        
        public SubjectSerialNumberCprUuidResponse()
        {
        }
        
        public SubjectSerialNumberCprUuidResponse(Lookup.CprUuidBySubjectSerialNumberResponse SubjectSerialNumberCprUuidResult)
        {
            this.SubjectSerialNumberCprUuidResult = SubjectSerialNumberCprUuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubjectSerialNumberCpr", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class SubjectSerialNumberCprRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string subjectSerialNumber;
        
        public SubjectSerialNumberCprRequest()
        {
        }
        
        public SubjectSerialNumberCprRequest(string subjectSerialNumber)
        {
            this.subjectSerialNumber = subjectSerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubjectSerialNumberCprResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class SubjectSerialNumberCprResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.CprBySubjectSerialNumberResponse SubjectSerialNumberCprResult;
        
        public SubjectSerialNumberCprResponse()
        {
        }
        
        public SubjectSerialNumberCprResponse(Lookup.CprBySubjectSerialNumberResponse SubjectSerialNumberCprResult)
        {
            this.SubjectSerialNumberCprResult = SubjectSerialNumberCprResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubjectSerialNumberRid", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class SubjectSerialNumberRidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string subjectSerialNumber;
        
        public SubjectSerialNumberRidRequest()
        {
        }
        
        public SubjectSerialNumberRidRequest(string subjectSerialNumber)
        {
            this.subjectSerialNumber = subjectSerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubjectSerialNumberRidResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class SubjectSerialNumberRidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.RidBySubjectSerialNumberResponse SubjectSerialNumberRidResult;
        
        public SubjectSerialNumberRidResponse()
        {
        }
        
        public SubjectSerialNumberRidResponse(Lookup.RidBySubjectSerialNumberResponse SubjectSerialNumberRidResult)
        {
            this.SubjectSerialNumberRidResult = SubjectSerialNumberRidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CprPid", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class CprPidRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string cpr;
        
        public CprPidRequest()
        {
        }
        
        public CprPidRequest(string cpr)
        {
            this.cpr = cpr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CprPidResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class CprPidResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.PidByCprResponse CprPidResult;
        
        public CprPidResponse()
        {
        }
        
        public CprPidResponse(Lookup.PidByCprResponse CprPidResult)
        {
            this.CprPidResult = CprPidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PidMatchesCpr", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class PidMatchesCprRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public string pid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=1)]
        public string cpr;
        
        public PidMatchesCprRequest()
        {
        }
        
        public PidMatchesCprRequest(string pid, string cpr)
        {
            this.pid = pid;
            this.cpr = cpr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PidMatchesCprResponse", WrapperNamespace="http://lookupservice.nemlog-in.dk", IsWrapped=true)]
    public partial class PidMatchesCprResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://lookupservice.nemlog-in.dk", Order=0)]
        public Lookup.PidMatchesCprResponse PidMatchesCprResult;
        
        public PidMatchesCprResponse1()
        {
        }
        
        public PidMatchesCprResponse1(Lookup.PidMatchesCprResponse PidMatchesCprResult)
        {
            this.PidMatchesCprResult = PidMatchesCprResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface LookupServiceChannel : Lookup.LookupService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LookupServiceClient : System.ServiceModel.ClientBase<Lookup.LookupService>, Lookup.LookupService
    {
        
        public LookupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Lookup.RidCprResponse RidCpr(Lookup.RidCprRequest request)
        {
            return base.Channel.RidCpr(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.RidCprResponse> RidCprAsync(Lookup.RidCprRequest request)
        {
            return base.Channel.RidCprAsync(request);
        }
        
        public Lookup.PidCprResponse PidCpr(Lookup.PidCprRequest request)
        {
            return base.Channel.PidCpr(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.PidCprResponse> PidCprAsync(Lookup.PidCprRequest request)
        {
            return base.Channel.PidCprAsync(request);
        }
        
        public Lookup.SubjectSerialNumberCprUuidResponse SubjectSerialNumberCprUuid(Lookup.SubjectSerialNumberCprUuidRequest request)
        {
            return base.Channel.SubjectSerialNumberCprUuid(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.SubjectSerialNumberCprUuidResponse> SubjectSerialNumberCprUuidAsync(Lookup.SubjectSerialNumberCprUuidRequest request)
        {
            return base.Channel.SubjectSerialNumberCprUuidAsync(request);
        }
        
        public Lookup.SubjectSerialNumberCprResponse SubjectSerialNumberCpr(Lookup.SubjectSerialNumberCprRequest request)
        {
            return base.Channel.SubjectSerialNumberCpr(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.SubjectSerialNumberCprResponse> SubjectSerialNumberCprAsync(Lookup.SubjectSerialNumberCprRequest request)
        {
            return base.Channel.SubjectSerialNumberCprAsync(request);
        }
        
        public Lookup.SubjectSerialNumberRidResponse SubjectSerialNumberRid(Lookup.SubjectSerialNumberRidRequest request)
        {
            return base.Channel.SubjectSerialNumberRid(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.SubjectSerialNumberRidResponse> SubjectSerialNumberRidAsync(Lookup.SubjectSerialNumberRidRequest request)
        {
            return base.Channel.SubjectSerialNumberRidAsync(request);
        }
        
        public Lookup.CprPidResponse CprPid(Lookup.CprPidRequest request)
        {
            return base.Channel.CprPid(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.CprPidResponse> CprPidAsync(Lookup.CprPidRequest request)
        {
            return base.Channel.CprPidAsync(request);
        }
        
        public Lookup.PidMatchesCprResponse1 PidMatchesCpr(Lookup.PidMatchesCprRequest request)
        {
            return base.Channel.PidMatchesCpr(request);
        }
        
        public System.Threading.Tasks.Task<Lookup.PidMatchesCprResponse1> PidMatchesCprAsync(Lookup.PidMatchesCprRequest request)
        {
            return base.Channel.PidMatchesCprAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
